### ISSUE TITLE
Projected density plot?

### ISSUE THREAD

**Issue by ttepperg** [nvaytet/osyris#48] opened 2021-12-21 00:08 UTC
Hi

I was wondering if it was possible to create a surface (i.e. projected) density plot (NOT a slice), in particular
of a gas disc. I have tried using the histogram2d() method, but the result is not as expected (see attached).

I have loaded the grid xy and the hydro density values into 'x', 'y,' and 'd', respectively, and used:

osyris.histogram2d(x,y,d,norm='log',xmin=290,xmax=310,ymin=290,ymax=310,vmin=1e4,vmax=1e9)

And the same for the xz projection.

The result looks highly pixelled, so I'm guessing the histogram is not being smoothed in any way internally
(which I though it would by looking at the examples). Also, the density units are wrong: they should be Msol / kpc^2.

Am I doing something wrong? Or is this not yet possible with the current version?

Perhaps it would be possible to plot a plane (e.g. slice) of arbitrary width?

Cheers

Thor
![disc_xy](https://user-images.githubusercontent.com/45543038/146848763-f65c73df-e8cc-4e94-b172-9414c8d0098f.png)
![disc_xz](https://user-images.githubusercontent.com/45543038/146848770-dffa4b0c-2b67-4815-a42f-ad61b6edb674.png)

**Comment by matthiasglz** [comment] 2021-12-22 13:29
Hi Thor,
this is related to the issue #17.
Neil has started to implement this feature in a branch [https://github.com/nvaytet/osyris/tree/column_density](https://github.com/nvaytet/osyris/tree/column_density).
I don't know if it works already in this branch but I guess it will be merged into the main branch when it's fully satisfactory.
Cheers,
Matthias

**Comment by nvaytet** [comment] 2021-12-27 18:14
Closing as duplicate of #17

**Closed by nvaytet** 2021-12-27 18:14 UTC

**Comment by nvaytet** [comment] 2022-01-20 10:40
Hi @ttepperg ,
How large is your data from the images you posted above? Is it possible to share?
I would like to run some tests with a first draft implementation of column density / thick slices.
Thanks!

**Comment by ttepperg** [comment] 2022-01-20 22:49
Hi @nvaytet,
That particular dataset is huge (3GB), due to an unfortunate choice
of Ramses grid + particle allocation parameters. But I could provide
another, smaller dataset, ~900MB, with a nice gas disk in it ;)
More than happy to share it, just let me know how would you prefer
to do it. I could, e.g. upload it to Dropbox and share a link?

Cheers

Thor

**Comment by nvaytet** [comment] 2022-01-21 09:09
@ttepperg Dropbox sounds great! Are you on the osyris Slack?
If not, I can add you there and you can send me the link there instead of publicly on github?

**Comment by ttepperg** [comment] 2022-01-22 00:38
@nvaytet

Yeah, good idea!
Please add me to the Slack channel.
